attr_des = {'pid': 'player id', 
              'tid': 'team id', 
              'fullname': 'full name',
              'pos': 'position',
              'age': 'age',
              'gp': 'game played',
              'mpg': 'minutes per game',
              'min': 'minutes percentage', 
              'usg': 'usage',
              'tor': 'turnover rate',
              'fta': 'freethrow attempt',
              'ft': 'freethrow percentage',
              'pa2': '2 Point Field Goal Attempts',
              'p2': '2 Point Field Goal Percentage',
              'pa3': '3 Point Field Goal Attempts',
              'p3': '3 Point Field Goal percentage',
              'efg': 'effective shooting percentage',
              'ts': 'True shooting percentage',
              'ppg': 'points per game', 
              'rpg': 'rebounds per game',
              'trb': 'total rebound percentage', 
              'apg': 'Assists per game', 
              'ast': 'Assists percentage', 
              'spg': 'steals per game', 
              'bpg': 'blocks per game', 
              'topg': 'turnovers per game', 
              'vi': 'Versatility Index', 
              'ortg': 'Offensive Rating', 
              'drtg': 'Defensive Rating',
              'team': 'team',
              'conf': 'conference',
              'division': 'division',
              'ptsgm': 'points per game',
              'aptsgm': 'points allowed per game', 
              'ptsdiff': 'points differential', 
              'pace': 'pace',
              'oeff': 'offensive efficiency',
              'deff': 'defensive efficiency', 
              'ediff': 'efficiency differential', 
              'sos': 'Strength of the Schedule', 
              'rsos': 'Remaining Strength of the Schedule', 
              'sar': 'Schedule Adjusted Rating', 
              'cons': 'consistency Rating', 
              'a4f': 'Adjusted 4 factors', 
              'w': 'Wins', 
              'l': 'Losses', 
              'win': 'Winning Percentage', 
              'ewin': 'Correlated Gaussian Expected Winning Percentage', 
              'pwin': 'Projected Winning percentage', 
              'ach': 'Achievement level in terms of winning', 
              'strk': 'Current Streaks'
              }

teams = [u'Atlanta Hawks', u'Boston Celtics', u'Brooklyn Nets', u'Charlotte Hornets', u'Chicago Bulls', u'Cleveland Cavaliers', u'Dallas Mavericks', u'Denver Nuggets', u'Detroit Pistons', u'Golden State Warriors', u'Houston Rockets', u'Indiana Pacers', u'Los Angeles Clippers', u'Los Angeles Lakers', u'Memphis Grizzlies', u'Miami Heat', u'Milwaukee Bucks', u'Minnesota Timberwolves', u'New Orleans Pelicans', u'New York Knicks', u'Oklahoma City Thunder', u'Orlando Magic', u'Philadelphia 76ers', u'Phoenix Suns', u'Portland Trail Blazers', u'Sacramento Kings', u'San Antonio Spurs', u'Toronto Raptors', u'Utah Jazz', u'Washington Wizards']
